# Generated by Django 6.0.7 on 2026-07-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('start_date', models.DateField(verbose_name='Hafızlığa Başlama Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('paused', 'Ara Verdi'), ('completed', 'Hafızlığını Tamamladı')], default='active', max_length=10, verbose_name='Aktiflik Durumu')),
                ('notes', models.TextField(blank=True, verbose_name='Açıklamalar')),
                ('target_completion_date', models.DateField(blank=True, help_text='Öğretici tarafından belirlenen hedef tarih (Hedef Sapması uyarısı için kullanılır).', null=True, verbose_name='Hedef Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Öğretici')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['full_name'],
            },
        ),
    ]
