# Generated by Django 6.0.7 on 2026-10-01 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yedek zamanı')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Dosya boyutu (bayt)')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='Kayıt sayısı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yedeği alan')),
            ],
            options={
                'verbose_name': 'Yedek kaydı',
                'verbose_name_plural': 'Yedek kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
