# Generated by Django 6.0.7 on 2026-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Yönetici'), ('teacher', 'Hafız Yetiştiricisi')], default='teacher', max_length=10, verbose_name='Rol'),
        ),
    ]
