# Generated by Django 6.0.7 on 2026-07-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveSmallIntegerField(verbose_name='Tekrar Başlangıç Sayfası')),
                ('end_page', models.PositiveSmallIntegerField(verbose_name='Tekrar Bitiş Sayfası')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_ranges', to='lessons.lessonrecord')),
            ],
            options={
                'verbose_name': 'Tekrar (Has) Kaydı',
                'verbose_name_plural': 'Tekrar (Has) Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='MemorizationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(verbose_name='Sayfa No')),
                ('status', models.CharField(choices=[('gray', 'Henüz Çalışılmadı'), ('yellow', 'Ezberlendi, Tekrar Gerekiyor'), ('green', 'Başarıyla Tamamlandı')], default='gray', max_length=10)),
                ('first_memorized_date', models.DateField(blank=True, null=True)),
                ('last_revised_date', models.DateField(blank=True, null=True)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='students.student')),
            ],
            options={
                'verbose_name': 'Hafızlık Sayfası',
                'verbose_name_plural': 'Hafızlık Sayfaları',
                'ordering': ['page_number'],
                'unique_together': {('student', 'page_number')},
            },
        ),
    ]
