# Generated by Django 6.0.7 on 2026-07-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonrecord_created_at_and_more'),
        ('memorization', '0001_initial'),
        ('students', '0002_alter_student_created_at_alter_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizationpage',
            name='first_memorized_date',
            field=models.DateField(blank=True, null=True, verbose_name='İlk Ezberlenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='memorizationpage',
            name='last_revised_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Tekrar Tarihi'),
        ),
        migrations.AlterField(
            model_name='memorizationpage',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Tekrar Sayısı'),
        ),
        migrations.AlterField(
            model_name='memorizationpage',
            name='status',
            field=models.CharField(choices=[('gray', 'Henüz Çalışılmadı'), ('yellow', 'Ezberlendi, Tekrar Gerekiyor'), ('green', 'Başarıyla Tamamlandı')], default='gray', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='memorizationpage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='students.student', verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='memorizationpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='revisionrecord',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_ranges', to='lessons.lessonrecord', verbose_name='Ders Kaydı'),
        ),
    ]
