# Generated by Django 6.1 on 2026-08-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_juzturcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorizationpage',
            name='synced_from_lessons',
            field=models.BooleanField(default=False, help_text="True ise bu sayfanın durumu günlük ders kayıtlarından (ham/has) otomatik hesaplanmıştır ve ders kaydı silinip/düzenlendiğinde yeniden hesaplanabilir. False ise 'Başlangıç Durumu Aktarımı' (bulk_apply_range) ile elle işaretlenmiştir ve ders senkronizasyonu bu sayfaları geri almaz/sıfırlamaz.", verbose_name='Ders Kaydından Senkronize'),
        ),
    ]
