# Generated by Django 6.1 on 2026-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_memorizationpage_synced_from_lessons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juzturcount',
            options={'ordering': ['juz_number'], 'verbose_name': 'Cüz Has Tekrar Sayacı', 'verbose_name_plural': 'Cüz Has Tekrar Sayaçları'},
        ),
        migrations.AlterField(
            model_name='juzturcount',
            name='last_tur_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Has Tekrar Tarihi'),
        ),
        migrations.AlterField(
            model_name='juzturcount',
            name='tur_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Has Tekrar Sayısı'),
        ),
    ]
