# Generated by Django 6.0.7 on 2026-07-18 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ders Tarihi')),
                ('attendance', models.CharField(choices=[('present', 'Geldi'), ('absent', 'Gelmedi'), ('excused', 'İzinli')], default='present', max_length=10, verbose_name='Devam Durumu')),
                ('ham_start_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ham Ders Başlangıç Sayfası')),
                ('ham_end_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ham Ders Bitiş Sayfası')),
                ('quality', models.CharField(blank=True, choices=[('excellent', 'Çok İyi'), ('good', 'İyi'), ('average', 'Orta'), ('weak', 'Zayıf')], max_length=10, null=True, verbose_name='Ders Kalitesi')),
                ('notes', models.TextField(blank=True, verbose_name='Günlük Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_records_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Günlük Ders Kaydı',
                'verbose_name_plural': 'Günlük Ders Kayıtları',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_memorization', models.PositiveSmallIntegerField(default=0, verbose_name='Günlük Toplam Ezber')),
                ('daily_revision', models.PositiveSmallIntegerField(default=0, verbose_name='Günlük Toplam Tekrar')),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attended', models.BooleanField(default=True)),
                ('cumulative_memorized_pages', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='students.student')),
            ],
            options={
                'verbose_name': 'Performans Geçmişi',
                'verbose_name_plural': 'Performans Geçmişleri',
                'ordering': ['date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
