# Generated by Django 6.0.7 on 2026-07-19 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('students', '0002_alter_student_created_at_alter_student_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_records_created', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Giren'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_records', to='students.student', verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='attended',
            field=models.BooleanField(default=True, verbose_name='Derse Geldi mi'),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='cumulative_memorized_pages',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Kümülatif Ezberlenen Sayfa'),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kalite Puanı'),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='students.student', verbose_name='Öğrenci'),
        ),
    ]
