# Generated by Django 6.1 on 2026-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='pismis_done',
            field=models.BooleanField(default=False, help_text="Yeni ham sayfasının hemen arkasından, aynı cüzde daha önce ezberlenmiş ('pişmiş') sayfaların da hocaya dinletildiğini onaylar.", verbose_name='Pişmiş (Ham Arkası) Okundu'),
        ),
    ]
