# Generated by Django 6.0.7 on 2026-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonrecord_pismis_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='pismis_page_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='pismis_done işaretliyse, ham arkasından kaç sayfa pişmiş okunduğunu isteğe bağlı olarak kaydeder (örn. öğrencinin pişmişte kaç sayfa geride kaldığını raporlamak için). Boş bırakılabilir.', null=True, verbose_name='Pişmiş Okunan Sayfa Sayısı'),
        ),
    ]
